### ISSUE TITLE
Import Swagger files

### ISSUE THREAD

**Issue by natenho** [natenho/Mockaco#9]
Generate templates based on swagger spec files.

**Comment by gevlee** [comment]
Hi,

I would like to help you with this feature, if you are intrested of course :)

**Comment by natenho** [comment]
Hello! Of course, I would appreciate that! I'm glad you're interested in
the project.

Feel free to send your code! ;-)

Em sex., 9 de out. de 2020 às 18:06, Arkadiusz Tymiński <
notifications@github.com> escreveu:

**Comment by ellerysammy** [comment]
Have had any progress on this ?
Just curious!!
It will a very good feature

**Comment by natenho** [comment]
@ellerysammy I agree that can be a good feature to have! I see a couple of commits on [atyminski fork](https://github.com/atyminski/Mockaco/commits/feature/9-import-swagger-files), but no movement since then. I'm also curious: are you using Mockaco for what kind of applications? Is it for personal use or in company?

Hey @atyminski! Do you have any plans to proceed implementing the feature?

**Comment by atyminski** [comment]
Hey @natenho. I have a busy time recently, so I haven't worked on that for more than year - sorry for that. I would like to continue the implementation if that's ok but it might take some time to finish it :)

**Comment by ellerysammy** [comment]
> @ellerysammy I agree that can be a good feature to have! I see a couple of commits on [atyminski fork](https://github.com/atyminski/Mockaco/commits/feature/9-import-swagger-files), but no movement since then. I'm also curious: are you using Mockaco for what kind of applications? Is it for personal use or in company?
> 
Hi, sorry for my late response, It's for personal stuff.
Definitely it will be a great functionality, I used to use mockaco for my initial mocks for the clients and one of them is a company that provide me yaml files

**Comment by StefanArcelor** [comment]
I'm trying to use the generator with a yaml file, but I'm getting this error
`[10:32:57 DBG]  OpenApi specification version: OpenApi2_0
[10:32:57 WRN]  OpenApi parser diagnostic error: (Lin: 12, Col: 20, Chr: 865) - (Lin: 12, Col: 20, Chr: 865): Mapping values are not allowed in this context. [#line=12]
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Mockaco.Templating.Generating.Providers.OpenApiTemplateProvider.BuildTemplates(OpenApiDocument openApiDocument)+MoveNext() in /home/runner/work/Mockaco/Mockaco/src/Mockaco.AspNetCore/Templating/Generating/Providers/OpenApiTemplateProvider.cs:line 42
   at Mockaco.Templating.Generating.Store.GeneratedTemplateStore.SaveAsync(IEnumerable`1 templates, CancellationToken cancellationToken) in /home/runner/work/Mockaco/Mockaco/src/Mockaco.AspNetCore/Templating/Generating/Store/GeneratedTemplateStore.cs:line 47
   at Mockaco.Templating.Generating.TemplatesGenerator.GenerateAsync(GeneratingOptions options, CancellationToken cancellationToken) in /home/runner/work/Mockaco/Mockaco/src/Mockaco.AspNetCore/Templating/Generating/TemplatesGenerator.cs:line 26
   at Mockaco.Templating.Generating.Cli.GeneratorRunner.ExecuteAsync(GeneratingOptions options, IConsole console, CancellationToken cancellationToken) in /home/runner/work/Mockaco/Mockaco/src/Mockaco.AspNetCore/Templating/Generating/Cli/GeneratorRunner.cs:line 21
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)`

Content around line 12 of the yaml:
![image](https://user-images.githubusercontent.com/116059370/196381657-936bfc95-87a6-4af9-bab8-256a564735a0.png)

Could you please help me in correcting the yaml ?

**Comment by StefanArcelor** [comment]
When using the generator I've noticed that the responses defined in the YAML are not part of the generated JSONs. Is there a way to generate the response bodies as well ?

h3. YAML
![image](https://user-images.githubusercontent.com/116059370/196384364-7c9c8f52-dc34-4d1c-9367-b08ebf175d14.png)

h3. Generated CreateUrgentProductionRequest.json
`{
  "request": {
    "method": "POST",
    "route": "/urgent-production-requests/"
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/json"
    }
  },
  "callbacks": []
}`
